<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8852" started-at="2022-07-14T13:01:35 ICT" finished-at="2022-07-14T13:01:44 ICT">
    <groups>
      <group name="run">
        <method signature="TestFiturSortBy.testBtnRoasted()[pri:0, instance:com.beangasm.TestFiturSortBy@80503]" name="testBtnRoasted" class="com.beangasm.TestFiturSortBy"/>
        <method signature="TestFiturSortBy.testSortByCheapest()[pri:0, instance:com.beangasm.TestFiturSortBy@80503]" name="testSortByCheapest" class="com.beangasm.TestFiturSortBy"/>
        <method signature="TestFiturSortBy.testSortByMostExpensive()[pri:0, instance:com.beangasm.TestFiturSortBy@80503]" name="testSortByMostExpensive" class="com.beangasm.TestFiturSortBy"/>
      </group> <!-- run -->
    </groups>
    <test name="Default test" duration-ms="8852" started-at="2022-07-14T13:01:35 ICT" finished-at="2022-07-14T13:01:44 ICT">
      <class name="com.beangasm.TestFiturSortBy">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.beangasm.TestFiturSortBy@80503]" name="setup" is-config="true" duration-ms="13162" started-at="2022-07-14T13:01:22 ICT" finished-at="2022-07-14T13:01:35 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="testBtnRoasted()[pri:0, instance:com.beangasm.TestFiturSortBy@80503]" name="testBtnRoasted" duration-ms="1255" started-at="2022-07-14T13:01:35 ICT" finished-at="2022-07-14T13:01:37 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBtnRoasted -->
        <test-method status="FAIL" signature="testSortByCheapest()[pri:0, instance:com.beangasm.TestFiturSortBy@80503]" name="testSortByCheapest" duration-ms="1747" started-at="2022-07-14T13:01:37 ICT" finished-at="2022-07-14T13:01:38 ICT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.beangasm.TestFiturSortBy.testSortByCheapest(TestFiturSortBy.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSortByCheapest -->
        <test-method status="FAIL" signature="testSortByMostExpensive()[pri:0, instance:com.beangasm.TestFiturSortBy@80503]" name="testSortByMostExpensive" duration-ms="5802" started-at="2022-07-14T13:01:38 ICT" finished-at="2022-07-14T13:01:44 ICT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.beangasm.TestFiturSortBy.testSortByMostExpensive(TestFiturSortBy.java:133)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSortByMostExpensive -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:com.beangasm.TestFiturSortBy@80503]" name="closeDriver" is-config="true" duration-ms="248" started-at="2022-07-14T13:01:44 ICT" finished-at="2022-07-14T13:01:44 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- com.beangasm.TestFiturSortBy -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
